"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
//import "./globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { Menu } from "@/components/Menu";
import { Login } from "@/components/Login";
import { useReducer } from "react";
import {init} from "../redux/init"
import {reducer} from "../redux/reducer"
import { Provider } from "../context/appCtx";
import "bootstrap/dist/css/bootstrap.css"
import { Loader } from "@/components/shared/Loader";
import { Toaster } from "@/components/shared/Toaster";

const inter = Inter({ subsets: ["latin"] });

//export const metadata: Metadata = {
  //title: "Create Next App",
  //description: "Generated by create next app",
//};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   const [state,dispatch]=useReducer(reducer,init);
   
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider value={{state,dispatch}}>
        {state?.isLoggedIn && <Menu />}
        {children}
          {/* state?.isLoggedIn?<Menu />:<Login /> */}
          
          {state?.isShowLoader && <Loader />}
         
        {state?.toaster?.isShowToaster && < Toaster />}
        </Provider>
        
        </body>
    </html>
  );
}
